out$rCode
                                                                   
 # matlab code to iterate an enhanced Nicholson-Bailey model"              
 # for host and parasite, with each capable of random (diffusive)"         
 #\tmovement.                                                       
                                                                        
hy <- h[t]exp[ r (1 - h[t]/k) - a*p[t] ]                             
py <- n*h(t) ( 1 - exp[- a*p(t) ] ) 
  
#Allowed to disperse using spatial 
  
h(t+1) = p_h(x,y) * hy                                           
p(t+1) = p_p(x,y) * py          

[20] "#"                                                                        
[21] "#\tp_h and p_p can be any probability functions representing the"          
[22] "#\tdispersal of the two species; I have used Gaussians below."             
[23] "#"                                                                        
[24] "#\tParameters appearing (and their interpretation):"                       
[25] "#"                                                                        
[26] "#\t\tr\treproduction rate of host  species"                                  
[27] "#\t\tk\tcarrying capacity of host species"                                   
[28] "#\t\ta\tencounter rate or effectiveness of parasite on host"                 
[29] "#\t\tn\tparasites produced by a successful infestation"                      
[30] "#"                                                                        
[31] "#\tParameters used for the code:"                                          
[32] "#"                                                                        
[33] "#\t\tnp\tnumber of points in x and y directions (a power of 2)"              
[34] "#\t\txl\tlength of domain in x and y directions"                             
[35] "#\t\tdx\tgrid spacing"                                                       
[36] "#\t\tdt\ta time-step length"                                                 
[37] "#\t\tmu\tfollowed by h and p -- diffusion parameter for each"                
[38] "#\t\t\t\tspecies"                                                             
[39] "#\t\tngens \tnumber of steps to run the code (number of"                     
[40] "#\t\t\tgenerations"                                                          
[41] "#"                                                                        
[42] "#"                                                                        
[43] "#"                                                                        
[44] ""                                                                         
[45] "#"                                                                        
[46] "#\tset parameters and spatial grids"                                       
[47] "#"                                                                        
[48] "np <- 128; mup <- .02; muh <- .02; dt <- .5; xl <- 10; dx <- 2*xl/np"     
[49] "x <- linspace(-xl,xl-dx,np)"                                              
[50] "y <- x"                                                                   
[51] "[X,Y] <- meshgrid(x,y)"                                                   
[52] "ngens <- 100"                                                             
[53] ""                                                                         
[54] "#"                                                                        
[55] "#\tset up spatial parameters" 
"#"                                                                        
[57] ""                                                                         
[58] "n <- ones(np)"                                                            
[59] "a <- 4*ones(np)"                                                          
[60] "r <- 1.75*ones(np)"                                                       
[61] "k <- ones(np)"                                                            
[62] " #\t    k=.01*ones(np)+(-.25<=X & X<=.25)+(abs(X)>=1.75 & abs(X)<=2.25)..."
[63] " #\t                              +(abs(X)>=3.75 & abs(X)<=4.25)..."       
[64] " #\t                              +(abs(X)>=5.75 & abs(X)<=6.25)..."       
[65] " #\t                              +(abs(X)>=7.75 & abs(X)<=8.25)..."       
[66] "  #\t                             +(abs(X)>=9.75 & abs(X)<=10.25);"        
[67] "kmax <- max(max(k))"                                                      
[68] ""                                                                         
[69] ""                                                                         
[70] "#"                                                                        
[71] "#\tSet up stuff for movie"                                                 
[72] "#"                                                                        
[73] "M <- moviein(ngens)#\tIf you want movies"                                  
[74] ""                                                                         
[75] "#"            
"#\tSet up initial conditions"                                              
[77] "#"                                                                        
[78] ""                                                                         
[79] "p0 <- .5*(1+cos(.5*pi*X/xl+pi/4*rand(np)).*sin(pi*Y/xl-pi/2*rand(np)))"   
[80] "h0 <- .5*rand(np).*(1+cos(4*pi*sqrt(X.^2+Y.^2)/xl))"                      
[81] ""                                                                         
[82] "#"                                                                        
[83] "#\tDefine movement kernels for host and parasite"                          
[84] "#"                                                                        
[85] ""                                                                         
[86] "hhker <- exp(-(X.^2+Y.^2)/(4*muh*dt))/(4*pi*dt*muh)*dx^2"                 
[87] "Fhker <- fft2(hhker)#\tFFT is taken because we will use it often,"         
[88] "\t\t\t# there are two factors of dx; one for each dimension"                 
[89] "pker <- exp(-(X.^2+Y.^2)/(4*mup*dt))/(4*pi*dt*mup)*dx^2"                  
[90] "Fpker <- fft2(pker)#\tFFT is taken because we will use it often"           
[91] "\t\t\t# there are two factors of dx; one for each dimennsion"                
[92] ""                                                                         
[93] "#"                                                                        
[94] "#\tNow we are in a position to iterate for"                                
[95] "# \ta number of generations equal to ngens"                                
[96] "#"                                                                        
[97] "for (j in 1:ngens){"                                                      
[98] ""                                                                         
[99] "#"         
"#\tAdvance the life cycles using adjusted N-B model"                       
[101] "#"                                                                        
[102] ""                                                                         
[103] "hn <- h0.*exp(r.*(1-h0./k)-a.*p0)"                                        
[104] "pn <- n.*h0.*(1-exp(-a.*p0))"                                             
[105] ""                                                                         
[106] "#"                                                                        
[107] "# \tDo the dispersal step"                                                 
[108] "#"                                                                        
[109] ""                                                                         
[110] "  fhn <- fft2(hn)#\tFirst take fft of each species"                        
[111] "  fpn <- fft2(pn)#\tFirst take fft of each species"                        
[112] ""                                                                         
[113] "#"                                                                        
[114] "#\tNow do the convolutions."                                               
[115] "#\tThe fftshift serves to center the probability functions."               
[116] "#"                                                                        
[117] "  h0 <- real(fftshift(ifft2(Fhker.*fhn)))){"                              
[118] "  p0 <- real(fftshift(ifft2(Fpker.*fpn)))){"                              
[119] ""                                                                         
[120] "#"                                                                        
[121] "#\tNow plot the solution"                                                  
[122] "#"      
""                                                                         
[124] "pcolor(X,Y,h0-p0), shading flat, colormap(hot), axis square, colorbar"    
[125] "#subplot(1,2,1)"                                                          
[126] "#pcolor(X,Y,h0),shading flat, colormap hot, title('Host'),colorbar"       
[127] "#subplot(1,2,2)"                                                          
[128] "#pcolor(X,Y,p0),shading flat, colormap jet, title('Parasite'),colorbar"   
[129] ""                                                                         
[130] "M(:,j) <- getframe#\tIf you want movies"                                   
[131] ""                                                                         
[132] "}"                                                                        
[133] "#"                                                                        
[134] "#\tHere ends the iteration"                                                
[135] "#"                                                                        
[136] ""                                                                         
[137] "#surf(X,Y,h0-p0), shading interp"                                         
[138] "#"                                                                        
[139] "#  To play the movie,  use this command:"                                 
[140] "#  movie(M,2,8)"                                                          
> 